# Generated by Django 4.2.6 on 2024-01-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_coursecategory_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(default='Course', max_length=120),
            preserve_default=False,
        ),
    ]
