"""
Django settings for twd project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import cloudinary
import cloudinary.api
import cloudinary.uploader
cloudinary.config(
    cloud_name =  'dvnflgqs2',
    api_key =  '975551641336967',
    api_secret =  'l12W5dcvd3JvHDr7Hi-Wyx9Q17c',
    )
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yk93+_bg!165r8=97(tel*(4+5$=w97dq&dshnf+@gpx8hpp&n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost','127.0.0.1','tech-with-dunamix.com','tech-with-dunamix.onrender.com']


# Application definition
SITE_ID = 1

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'core.apps.CoreConfig',
    'mezzanine',
    'ckeditor',
    'ckeditor_uploader',
    'cloudinary'
]

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js'
CKEDITOR_UPLOAD_PATH = 'uploads/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middlewares.CoreMiddleWare'
]

ROOT_URLCONF = 'twd.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'twd.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

#DATABASES = {
 #   'default': {
  #      'ENGINE': 'django.db.backends.sqlite3',
   #     'NAME': BASE_DIR / 'db.sqlite3',
    #}
#}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'verceldb',  # Your database name
        'USER': 'default',   # Your database user
        'PASSWORD': '4kSCf6tMHFcT',  # Your database password
        'HOST': 'ep-mute-mountain-a1rg7bs4-pooler.ap-southeast-1.aws.neon.tech',  # Your database host
        'PORT': '5432',  # Your database port
        'OPTIONS': {
            'sslmode': 'require',  # This enables SSL mode
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
   
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
   
    
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
DEVELOPMENT_MODE = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATCI_ROOT = 'staticfile'
STATICFILES_DIRS = ['static']
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#AUTH

AUTH_USER_MODEL = 'core.User'
AUHTENTICATION_BACKENDS = ['core.utils.Auth']
JQUERY_UI_FILENAME = "jquery-ui.min.js"
PACKAGE_NAME_FILEBROWSER = "filebrowser_safe"
CKEDITOR_JQUERY_URL = 'https://code.jquery.com/jquery-3.6.4.min.js'  # Replace with the latest version

CKEDITOR_CONFIGS = {
    'default': {
        'width': '100%',  # Set the editor width
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Source', '-', 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-'],
            ['NumberedList', 'BulletedList', 'Blockquote', '-'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-'],
            ['Link', 'Unlink', 'CodeSnippet','Table', 'HorizontalRule'],
            ['RemoveFormat', 'Styles', 'Format', 'Font', 'FontSize', 'TextColor', 'BGColor', '-'],
        ],
        'extraPlugins': 'codesnippet,justify,uploadimage',
        'codeSnippet_theme': 'github',  # Choose your preferred code snippet theme
        'autoGrow_minHeight': 200,
        'autoGrow_bottomSpace': 10,
        'uploadUrl': '/ckeditor/upload/',  # URL for handling image uploads
        'filebrowserBrowseUrl': '/ckeditor/browse/',  # URL for browsing server files
        'filebrowserImageBrowseUrl': '/ckeditor/browse/',  # URL for browsing server images
        'filebrowserUploadUrl': '/ckeditor/upload/',  # URL for handling file uploads
        'filebrowserImageUploadUrl': '/ckeditor/upload/',  # URL for handling image uploads
    },
}
